// FIXME: Shared workspace로 나중에 이동

export const ErrorCodes = {
	// 데이터베이스 관련 에러
	DUPLICATE_ENTRY: '23505',
	FOREIGN_KEY_VIOLATION: '23503',
	UNDEFINED_COLUMN: '42703',

	// 인증 관련 에러
	UNAUTHORIZED: '401',
	FORBIDDEN: '403',

	// 네트워크 관련 에러
	NETWORK_ERROR: 'NETWORK_ERROR',
	TIMEOUT: 'TIMEOUT',

	// 서버 관련 에러
	INTERNAL_SERVER_ERROR: '500',
	SERVICE_UNAVAILABLE: '503',

	// 클라이언트 관련 에러
	BAD_REQUEST: '400',
	NOT_FOUND: '404',

	// 커스텀 에러
	VALIDATION_ERROR: 'VALIDATION_ERROR',
	UNKNOWN_ERROR: 'UNKNOWN_ERROR',

	// API 특정 에러
	RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
	INVALID_API_KEY: 'INVALID_API_KEY',

	// 비즈니스 로직 관련 에러
	INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
	PRODUCT_OUT_OF_STOCK: 'PRODUCT_OUT_OF_STOCK',
};
